name: ci-cd
on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: pdo_mysql, mbstring, exif, pcntl, bcmath, zip, gd, sodium, predis
      - uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: '5.0.6'
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.test.example', '.env');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Create Database
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: |
          mkdir -p database
          touch database/database.sqlite
          php artisan migrate
          php artisan db:seed
